
# autogenerated from picocli command line arguments in TauP
# For The TauP Toolkit, version: 3.2.2-SNAPSHOT_2026-09-11T165623

from .dataclass import VelocityModel

class VelmergeQuery:
  def __init__(self):
    self.toolname= "velmerge"

    self._elev=None
    self._model=None
    self._smoothbot=None
    self._smoothtop=None
    self._velocitymodelmergetext=None
    self._velocitymodeltext=None

  def calc(self, taupServer):
    """
    Sends all params to the server, returns the result parsed from JSON into dataclasses.
    """
    return VelocityModel.from_json(self.calcJson(taupServer))

  def asCommandLine(self, taupServer):
    """
    Sends all params to the server, returns the equivalent command line.
    """
    params = self.create_params()
    return taupServer.asCommandLine(params, self.toolname)


  def calcJson(self, taupServer):
    """
    Sends all params to the server, returns the result parsed from JSON.
    """
    params = self.create_params()
    return taupServer.queryJson(params, self.toolname)


  def get_elev(self):
    """
    returns current value of elev as a Float
    """
    return self._elev

  def elev(self, val):
    """
    Sets the elev parameter, of type Float

    modify topmost layers for an elevation (meters), may be negative

    Known as ``--elev`` in command line.

    :param val: value to set elev to
    """
    self._elev = val
    return self

  def get_mod(self):
    """
    returns current value of model as a String
    """
    return self._model

  def mod(self, val):
    """
    Sets the model parameter, of type String

    use velocity model "modelname" for calculations, format is guessed.

    Known as ``--mod`` in command line.
    Also known as ``--model`` in command line.

    :param val: value to set model to
    """
    self._model = val
    return self

  def get_model(self):
    """
    returns current value of model as a String
    """
    return self._model

  def model(self, val):
    """
    Sets the model parameter, of type String

    use velocity model "modelname" for calculations, format is guessed.

    Known as ``--model`` in command line.

    :param val: value to set model to
    """
    self._model = val
    return self

  def get_smoothbot(self):
    """
    returns current value of smoothbot as a Boolean
    """
    return self._smoothbot

  def smoothbot(self, val=True):
    """
    Sets the smoothbot parameter, of type Boolean

    Without arguments sets the value to True. 

    smooth merge at bottom

    Known as ``--smoothbot`` in command line.

    :param val: value to set smoothbot to
    """
    self._smoothbot = val
    return self

  def get_smoothtop(self):
    """
    returns current value of smoothtop as a Boolean
    """
    return self._smoothtop

  def smoothtop(self, val=True):
    """
    Sets the smoothtop parameter, of type Boolean

    Without arguments sets the value to True. 

    smooth merge at top

    Known as ``--smoothtop`` in command line.

    :param val: value to set smoothtop to
    """
    self._smoothtop = val
    return self

  def get_velocitymodelmergetext(self):
    """
    returns current value of velocitymodelmergetext as a String
    """
    return self._velocitymodelmergetext

  def velocitymodelmergetext(self, val):
    """
    Sets the velocitymodelmergetext parameter, of type String

    Velocity merge model as json to load for calculations, similar to --modmerge but is text instead of a file or name

    Known as ``--velocitymodelmergetext`` in command line.

    :param val: value to set velocitymodelmergetext to
    """
    self._velocitymodelmergetext = val
    return self

  def get_velocitymodeltext(self):
    """
    returns current value of velocitymodeltext as a String
    """
    return self._velocitymodeltext

  def velocitymodeltext(self, val):
    """
    Sets the velocitymodeltext parameter, of type String

    Velocity model as json to load for calculations, similar to --model but is text instead of a file or name

    Known as ``--velocitymodeltext`` in command line.

    :param val: value to set velocitymodeltext to
    """
    self._velocitymodeltext = val
    return self


  def create_params(self):
    """
    Create dict of params suitible for passing to requests query call.
    """
    params = {
      "format": "json",
    }
    if self._elev is not None:
      params["elev"] = self._elev
    if self._model is not None:
      params["model"] = self._model
    if self._smoothbot is not None:
      params["smoothbot"] = self._smoothbot
    if self._smoothtop is not None:
      params["smoothtop"] = self._smoothtop
    if self._velocitymodelmergetext is not None:
      params["velocitymodelmergetext"] = self._velocitymodelmergetext
    if self._velocitymodeltext is not None:
      params["velocitymodeltext"] = self._velocitymodeltext
    return params

