
# autogenerated from picocli command line arguments in TauP
# For The TauP Toolkit, version: 3.0.2-SNAPSHOT_2025-07-14T122228

class VelmergeQuery:
  def __init__(self):
    self.toolname= "velmerge"

    self._elev=None
    self._model=None
    self._modmerge=None
    self._ndmerge=None
    self._smoothbot=None
    self._smoothtop=None
    self._tvelmerge=None

  def calcJson(self, taupServer):
    """
    Sends all params to the server, returns the result parsed from JSON.
    """
    params = self.create_params()
    return taupServer.queryJson(params, self.toolname)


  def get_elev(self):
    """
    returns current value of elev as a Float
    """
    return self._elev

  def elev(self, val):
    """
    Sets the elev parameter, of type Float

    increase topmost layer by elevation (meters)

    Known as --elev in command line.

    :param val: value to set elev to
    """
    self._elev = val
    return self

  def get_mod(self):
    """
    returns current value of model as a String
    """
    return self._model

  def mod(self, val):
    """
    Sets the model parameter, of type String

    use velocity model "modelname" for calculations, format is guessed.

    Known as --mod in command line.
    Also known as --model in command line.

    :param val: value to set model to
    """
    self._model = val
    return self

  def get_model(self):
    """
    returns current value of model as a String
    """
    return self._model

  def model(self, val):
    """
    Sets the model parameter, of type String

    use velocity model "modelname" for calculations, format is guessed.

    Known as --model in command line.

    :param val: value to set model to
    """
    self._model = val
    return self

  def get_modmerge(self):
    """
    returns current value of modmerge as a String
    """
    return self._modmerge

  def modmerge(self, val):
    """
    Sets the modmerge parameter, of type String

    velocity file to merge, format is guessed

    Known as --modmerge in command line.

    :param val: value to set modmerge to
    """
    self._modmerge = val
    return self

  def get_ndmerge(self):
    """
    returns current value of ndmerge as a String
    """
    return self._ndmerge

  def ndmerge(self, val):
    """
    Sets the ndmerge parameter, of type String

    "named discontinuities" velocity file to merge

    Known as --ndmerge in command line.

    :param val: value to set ndmerge to
    """
    self._ndmerge = val
    return self

  def get_smoothbot(self):
    """
    returns current value of smoothbot as a Boolean
    """
    return self._smoothbot

  def smoothbot(self, val):
    """
    Sets the smoothbot parameter, of type Boolean

    smooth merge at bottom

    Known as --smoothbot in command line.

    :param val: value to set smoothbot to
    """
    self._smoothbot = val
    return self

  def get_smoothtop(self):
    """
    returns current value of smoothtop as a Boolean
    """
    return self._smoothtop

  def smoothtop(self, val):
    """
    Sets the smoothtop parameter, of type Boolean

    smooth merge at top

    Known as --smoothtop in command line.

    :param val: value to set smoothtop to
    """
    self._smoothtop = val
    return self

  def get_tvelmerge(self):
    """
    returns current value of tvelmerge as a String
    """
    return self._tvelmerge

  def tvelmerge(self, val):
    """
    Sets the tvelmerge parameter, of type String

    ".tvel" velocity file to merge, ala ttimes

    Known as --tvelmerge in command line.

    :param val: value to set tvelmerge to
    """
    self._tvelmerge = val
    return self


  def create_params(self):
    """
    Create dict of params suitible for passing to requests query call.
    """
    params = {
      "format": "json",
    }
    if self._elev is not None:
      params["elev"] = self._elev
    if self._model is not None:
      params["model"] = self._model
    if self._modmerge is not None:
      params["modmerge"] = self._modmerge
    if self._ndmerge is not None:
      params["ndmerge"] = self._ndmerge
    if self._smoothbot is not None:
      params["smoothbot"] = self._smoothbot
    if self._smoothtop is not None:
      params["smoothtop"] = self._smoothtop
    if self._tvelmerge is not None:
      params["tvelmerge"] = self._tvelmerge
    return params

